### ISSUE TITLE
Future Builder for fetching Location

### ISSUE THREAD

**Issue by monucode** [dragosholban/FlutterWeatherApp#1]
E/flutter (12972): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter (12972): type '() => Future<Map<String, double>>' is not a subtype of type 'Map<String, double>' in type cast
E/flutter (12972): #0      Object._as (dart:core/runtime/libobject_patch.dart:78:25)
E/flutter (12972): #1      MyAppState.loadWeather (file:///C:/Users/agsin_x1pzwu8/Downloads/FlutterWeatherApp-master/FlutterWeatherApp-master/lib/main.dart:104:40)
E/flutter (12972): <asynchronous suspension>
E/flutter (12972): #2      MyAppState.initState (file:///C:/Users/agsin_x1pzwu8/Downloads/FlutterWeatherApp-master/FlutterWeatherApp-master/lib/main.dart:33:5)
E/flutter (12972): #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3787:58)
E/flutter (12972): #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
E/flutter (12972): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
E/flutter (12972): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
E/flutter (12972): #7      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:901:16)
E/flutter (12972): #8      RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:872:5)
E/flutter (12972): #9      RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:818:17)
E/flutter (12972): #10     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2253:19)
E/flutter (12972): #11     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:817:13)
E/flutter (12972): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:709:7)
E/flutter (12972): #13     runApp (package:flutter/src/widgets/binding.dart:748:7)
E/flutter (12972): #14     main (file:///C:/Users/agsin_x1pzwu8/Downloads/FlutterWeatherApp-master/FlutterWeatherApp-master/lib/main.dart:12:16)
E/flutter (12972): #15     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
E/flutter (12972): #16     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

**Comment by bew1769** [comment]
Line 102 of main.dart needs () after .getLocation ->.getLocation()
